spring:
  data:
    mongodb:
#      uri: ${MONGOLAB_ORANGE_URI}
      database: token-generator
      host: localhost
#      username: admin
#      password: adminio
      port: 27017
  jackson:
    property-naming-strategy: SNAKE_CASE
    application:
      name: tonken_generator

server:
  port: 8089