spring:
  data:
    mongodb:
      database: token-generator
      host: mongodb+srv://admin:adminio@cluster0-yaekv.mongodb.net/test?retryWrites=true&w=majority
#      port: 27017
  jackson:
    property-naming-strategy: SNAKE_CASE
    application:
      name: tonken_generator

server:
  port: 8089