spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:adminio@cluster0-yaekv.mongodb.net/token-generator?retryWrites=true&w=majority
#      database: token-generator 
#      host:
#      username: admin
#      password: adminio
#      port: 27017
  jackson:
    property-naming-strategy: SNAKE_CASE
    application:
      name: tonken_generator

server:
  port: 8089